### PR TITLE
Fix MemToReg

### LINKED ISSUE #812: Uninitialized register after MemToReg
We have problems with [this file](https://github.com/user-attachments/files/19024089/check_cachedq_vmm.zip) (coming from [here](https://github.com/open-s4c/libvsync/blob/lilith/pre-release-4.1.0/verify/cachedq/cachedq_verify.c)). 

This is how (part of) the IR looks just before `MemToReg`
```
[2] function bv64 reader(bv64 r0)
462:  l1:
463:     bv64 r2 <- stackalloc(type=bv64, size=bv64(1), align=bv64(8))
464:     bv64 r3 <- stackalloc(type=bv32, size=bv64(1), align=bv64(4))
465:     bv64 r4 <- stackalloc(type=bv32, size=bv64(1), align=bv64(4))
466:     bv64 r5 <- stackalloc(type=[1 x bv64], size=bv64(1), align=bv64(8))
467:     bv64 r6 <- stackalloc(type=bv64, size=bv64(1), align=bv64(8))
468:     bv64 r7 <- stackalloc(type=bv64, size=bv64(1), align=bv64(8))
469:     store(*bv64 r2, bv64 r0)
470:     bv64 r8 = load(*bv64 r2)
471:     bv64 r9 <- bv64 r8
472:     bv32 r10 = load(*bv64 r9)
473:     store(*bv64 r3, bv32 r10)
474:     store(*bv64 r4, bv32(0))
475:  l11.loop:
476:     bv32 r12 = load(*bv64 r4)
477:     bv1 r13 <- (bv32 r12 < bv32(2)) ? bv1(1) : bv1(0)
478:     if(bv1 r13 != bv1(0)); then goto l11.l14
479:     goto l11.l39
```
and this is how it looks after it (noticed the use of uninitialized `r4` by event `418`)
```
[2] function bv64 reader(bv64 r0)
409:  l1:
410:     bv64 r5 <- stackalloc(type=[1 x bv64], size=bv64(1), align=bv64(8))
411:     bv64 DUMMY_REG_0 <- bv64 r0
412:     bv64 r8 <- bv64 DUMMY_REG_0
413:     bv64 r9 <- bv64 r8
414:     bv32 r10 = load(*bv64 r9)
415:     bv32 DUMMY_REG_1 <- bv32 r10
416:     bv32 DUMMY_REG_2 <- bv32(0)
417:  l11.loop:
418:     bv32 r12 = load(*bv64 r4)
419:     bv1 r13 <- (bv32 r12 < bv32(2)) ? bv1(1) : bv1(0)
420:     if(bv1 r13 != bv1(0)); then goto l11.l14
421:     goto l11.l39
```

### PR DESCRIPTION
**Pull request by xeren**
This PR should fix #812.  The former implementation missed a check for dead code when merging control paths.  This bug lead to inconsistent register promotion, whenever some register holding the address of a promotable object is live at such a merging.

### CODE REVIEW

**Comment by hernanponcedeleon** [comment]
The pass is still buggy. This is how the IR looks before the **second** call to `MemToReg`
```
[2] thread bv64 reader(bv64 r0)
908:     ThreadStart by T0:main::ThreadCreate(T2:reader, bv64 r62)
909:     bool __startT2 = load(*&__com2__reader, ACQ)
910:     assume(bool __startT2)
911:     bv64 r0 := Argument(0) from ThreadCreate(T2:reader, bv64 r62)
912:  l1:
913:     bv64 r5 <- stackalloc(type=[1 x bv64], size=bv64(1), align=bv64(8))
914:     bv32 r10 = load(*bv64 r0)
915:     #__VERIFIER_loop_bound(bv32(3))
916:  l11.loop/itr_1:
917:     { 0: bv32 } __localLiveSnapshot#8 <- { bv32(0) }
-1:      === Calling intrinsic llvm.memset.p0i8.i64 ===
-1:      store(*bv64 r5 + bv64(0), bv8(0))
-1:      store(*bv64 r5 + bv64(1), bv8(0))
-1:      store(*bv64 r5 + bv64(2), bv8(0))
-1:      store(*bv64 r5 + bv64(3), bv8(0))
-1:      store(*bv64 r5 + bv64(4), bv8(0))
-1:      store(*bv64 r5 + bv64(5), bv8(0))
-1:      store(*bv64 r5 + bv64(6), bv8(0))
-1:      store(*bv64 r5 + bv64(7), bv8(0))
-1:      === Returning from intrinsic llvm.memset.p0i8.i64 ===
```
and this is how it looks after
```
[2] thread bv64 reader(bv64 r0)
899:     ThreadStart by T0:main::ThreadCreate(T2:reader, bv64 r62)
900:     bool __startT2 = load(*&__com2__reader, ACQ)
901:     assume(bool __startT2)
902:     bv64 r0 := Argument(0) from ThreadCreate(T2:reader, bv64 r62)
903:  l1:
904:     bv32 r10 = load(*bv64 r0)
905:     #__VERIFIER_loop_bound(bv32(3))
906:  l11.loop/itr_1:
907:     { 0: bv32 } __localLiveSnapshot#8 <- { bv32(0) }
908:     === Calling intrinsic llvm.memset.p0i8.i64 ===
909:     bv64 DUMMY_REG_67 <- zext bv8(0) to bv64
910:     store(*bv64 r5 + bv64(1), bv8(0))
911:     store(*bv64 r5 + bv64(2), bv8(0))
912:     store(*bv64 r5 + bv64(3), bv8(0))
913:     store(*bv64 r5 + bv64(4), bv8(0))
914:     store(*bv64 r5 + bv64(5), bv8(0))
915:     store(*bv64 r5 + bv64(6), bv8(0))
916:     store(*bv64 r5 + bv64(7), bv8(0))
917:     === Returning from intrinsic llvm.memset.p0i8.i64 ===
```
Notice that `r5 <- stackalloc` is removed even if `r5` is used in `memset`

File: dartagnan/src/main/java/com/dat3m/dartagnan/program/processing/MemToReg.java [hunk 1]
```diff
@@ -313,6 +314,15 @@ private void publishRegisters(Set<Register> registers) {
             }
         }
 
+        private AddressOffset toAddressOffset(MemoryCoreEvent event, RegisterOffset gep) {
+            assert gep == null || gep.register != null;
```
Comment (hernanponcedeleon) [inline dartagnan/src/main/java/com/dat3m/dartagnan/program/processing/MemToReg.java:318]: Shouldn't this be `assert gep != null || gep.register != null;`?
If `gep` is null, then `gep.register` will throw an exception

Comment (xeren) [reply dartagnan/src/main/java/com/dat3m/dartagnan/program/processing/MemToReg.java:318]: This is an implication, that allows `gep` to be null

**Comment by xeren** [comment]
The pass failed to promote byte accesses to higher bytes.  This happened, because the promotion algorithm failed to assign a proper access type for them, as the allocated type is `bv64`.  The recent patch should consistently detect the object as unpromotable.  It should be possible to promote these accesses, as well.  You may merge, if the checks work now.

File: dartagnan/src/main/java/com/dat3m/dartagnan/program/processing/MemToReg.java (hunk 1 above)
Comment (hernanponcedeleon) [reply dartagnan/src/main/java/com/dat3m/dartagnan/program/processing/MemToReg.java:318]: I can never get the re-write of an implication right when reading code :/

**Comment by hernanponcedeleon** [comment]
I confirm we now return the expected result on the benchmark. 

I will take a closer look to the changes in the code later.

**Comment by hernanponcedeleon** [comment]
I am ok with the code changes. I will merge once the test is added and the CI passes.
