### PR TITLE
Fix help option in native mode

### LINKED ISSUE #983: Option --help does not work in native mode
Guava’s ClassPath (used in `OptionInfo`) does not work reliably in native images so we might need a different solution than the current one.

### PR DESCRIPTION
**Pull request by hernanponcedeleon**
Fixes #983.

As a side-effect: now the outcome is immediate, while in the past it took a few seconds to collect all classes.

### CODE REVIEW

File: dartagnan/src/main/java/com/dat3m/dartagnan/configuration/OptionInfo.java [hunk 1]
```diff
@@ -14,65 +14,62 @@
...
+                "com.dat3m.dartagnan.wmm.Wmm$Config",
+                "com.dat3m.dartagnan.wmm.analysis.RelationAnalysis$Config",
+                "com.dat3m.dartagnan.wmm.analysis.WmmAnalysis",
+                "com.dat3m.dartagnan.wmm.processing.WmmProcessingManager"
+        ).map(name -> {
+            try {
+                return Class.forName(name);
+            } catch (ClassNotFoundException e) {
+                throw new RuntimeException("Cannot load class: " + name, e);
+            }
```
Comment (ThomasHaas) [inline dartagnan/src/main/java/com/dat3m/dartagnan/configuration/OptionInfo.java]: Can't you just list the classes explicitly e.g.,`WmmAnalysis.class` or are some private inner classes not accessible this way? Because with an explicit listing, the code becomes robust against refactoring/renaming

Comment (hernanponcedeleon) [reply dartagnan/src/main/java/com/dat3m/dartagnan/configuration/OptionInfo.java]: No, `Class.forName` requires the fully qualified name of the desired class.

Comment (ThomasHaas) [reply dartagnan/src/main/java/com/dat3m/dartagnan/configuration/OptionInfo.java]: My point is that you don't need to call `Class.forName` at all, you can just write a big list like this:
```Java
return Stream.of(
   WmmAnalysis.class,
   WmmProcessingManager.class,
   OptionNames.class,
   ...
)
```
The only limitation I can think of is that you cannot access private inner classes this way. I'm not sure if we have such classes. And even if, we could make them public as long as their constructor remains private.

Comment (hernanponcedeleon) [reply dartagnan/src/main/java/com/dat3m/dartagnan/configuration/OptionInfo.java]: How would I call `Options o = c.getAnnotation(Options.class);` if I do not have access to the class?

> I'm not sure if we have such classes.

We do have them ... see the strings having `$`

Comment (ThomasHaas) [reply dartagnan/src/main/java/com/dat3m/dartagnan/configuration/OptionInfo.java]: I don't understand. The stream still returns all classes just like before. The only difference is that you don't do a lookup by name but instead just put the class reference directly. 
I think that, e.g., `Class.fromName("com.dat3m.dartagnan.Dartagnan") == Dartagnan.class` will hold. Unless `Class.fromName` does more than just returning the class instance.

Comment (hernanponcedeleon) [reply dartagnan/src/main/java/com/dat3m/dartagnan/configuration/OptionInfo.java]: Ok, now I got what the suggestion was

File: dartagnan/src/main/java/com/dat3m/dartagnan/program/analysis/alias/AliasAnalysis.java [hunk 2]
```diff
@@ -77,7 +77,7 @@ static AliasAnalysis fromConfig(Program program, Context analysisContext, Config
     }
 
     @Options
-    final class Config {
+    public final class Config {
```
Comment (ThomasHaas) [inline dartagnan/src/main/java/com/dat3m/dartagnan/program/analysis/alias/AliasAnalysis.java:80]: FYI, I think inner classes of interfaces are always public by default. In fact, you cannot even make them private.
But you can keep the explicit public modifier.

**Review by ThomasHaas — APPROVED** [review]
LGTM
