### PR TITLE
Throw descriptive error msg when the requirements of field_insensitiv…

### LINKED ISSUE #883: NULL pointer in FIELD_INSENSITIVE alias analysis
```
./Dartagnan-SVCOMP.sh ../sv-benchmarks/c/properties/unreach-call.prp ../sv-benchmarks/c/weaver/popl20-bad-counter-queue.wvr.c

...

========================================
[13.05.2025] 19:54:28 [INFO] AliasAnalysis.fromConfig - Selected alias analysis: FIELD_INSENSITIVE
[13.05.2025] 19:54:28 [ERROR] Dartagnan.main - null
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:496) ~[guava-32.1.2-jre.jar:?]
        at com.dat3m.dartagnan.program.memory.MemoryObject.getKnownSize(MemoryObject.java:68) ~[dartagnan.jar:?]
        at com.dat3m.dartagnan.program.analysis.alias.AndersenAliasAnalysis.<init>(AndersenAliasAnalysis.java:56) ~[dartagnan.jar:?]
        at com.dat3m.dartagnan.program.analysis.alias.AndersenAliasAnalysis.fromConfig(AndersenAliasAnalysis.java:65) ~[dartagnan.jar:?]
        at com.dat3m.dartagnan.program.analysis.alias.AliasAnalysis.fromConfig(AliasAnalysis.java:43) ~[dartagnan.jar:?]
        at com.dat3m.dartagnan.verification.solving.ModelChecker.performStaticProgramAnalyses(ModelChecker.java:87) ~[dartagnan.jar:?]
        at com.dat3m.dartagnan.verification.solving.AssumeSolver.run(AssumeSolver.java:51) ~[dartagnan.jar:?]
        at com.dat3m.dartagnan.verification.solving.AssumeSolver.run(AssumeSolver.java:39) ~[dartagnan.jar:?]
        at com.dat3m.dartagnan.Dartagnan.main(Dartagnan.java:223) [dartagnan.jar:?]
ERROR
```

### PR DESCRIPTION
**Pull request by hernanponcedeleon**
…e alias analysis are not satisfied.

Fixes #883.

### CODE REVIEW

**Review by ThomasHaas — APPROVED** [review]
LGTM.

EDIT: Actually, you might also want to add such a check to `FieldSensitiveAnalysis`. That one cannot handle unknown allocations either I think.

**Comment by ThomasHaas** [comment]
While you are at it, you might as well add an error message to the checkState call in `getKnownSize`.

File: dartagnan/src/main/java/com/dat3m/dartagnan/program/memory/MemoryObject.java [hunk 1]
```diff
@@ -65,7 +65,7 @@ public class MemoryObject extends LeafExpressionBase<Type> {
     public Expression size() { return size; }
     public boolean hasKnownSize() { return size instanceof IntLiteral; }
     public int getKnownSize() {
-        Preconditions.checkState(hasKnownSize());
+        Preconditions.checkState(hasKnownSize(), String.format("Cannot call method getKnownSize() for object %s with unknown size", this));
```
Comment (ThomasHaas) [inline dartagnan/src/main/java/com/dat3m/dartagnan/program/memory/MemoryObject.java:68]: You don't need String.format here becaue it is built into the `checkState` method:
```
Preconditions.checkState(hasKnownSize(), "Cannot call getKnownSize() for object %s with unknown size", this).
```
